spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  data:
    redis:
      host: redis

server:
  forward-headers-strategy: framework

frontend:
  base-url: ${FRONTEND_BASE_URL:https://semo-xi.vercel.app}

management:
  metrics:
    tags:
      env: prod
