CREATE TABLE problem_scan (
	id BIGINT NOT NULL AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	status VARCHAR(20) NOT NULL,
	has_figure TINYINT(1) NOT NULL,
	render_mode VARCHAR(20) NOT NULL,
	ocr_plain_text MEDIUMTEXT NULL,
	ocr_raw_json JSON NULL,
	ai_draft_json JSON NULL,
	predicted_unit_id VARCHAR(50) NULL,
	predicted_type_id VARCHAR(50) NULL,
	confidence DECIMAL(4, 3) NULL,
	needs_review TINYINT(1) NOT NULL,
	ai_problem_latex MEDIUMTEXT NULL,
	ai_solution_latex MEDIUMTEXT NULL,
	ai_answer_format VARCHAR(20) NULL,
	ai_answer_value VARCHAR(255) NULL,
	ai_answer_choice_no INT NULL,
	ai_choices_json JSON NULL,
	ai_unit_candidates_json JSON NULL,
	ai_type_candidates_json JSON NULL,
	ocr_attempt_count INT NOT NULL,
	ai_attempt_count INT NOT NULL,
	next_retry_at DATETIME(6) NULL,
	locked_at DATETIME(6) NULL,
	lock_owner VARCHAR(64) NULL,
	ocr_completed_at DATETIME(6) NULL,
	ai_completed_at DATETIME(6) NULL,
	fail_reason VARCHAR(255) NULL,
	lock_token VARCHAR(40) NULL,
	created_at DATETIME(6) NOT NULL,
	updated_at DATETIME(6) NOT NULL,
	PRIMARY KEY (id),
	KEY idx_problem_scan_user_created (user_id, created_at),
	KEY idx_problem_scan_status_retry (status, next_retry_at),
	KEY idx_problem_scan_status_locked (status, locked_at),
	KEY idx_problem_scan_pred_unit (predicted_unit_id),
	KEY idx_problem_scan_pred_type (predicted_type_id),
	KEY idx_problem_scan_render_created (render_mode, created_at),
	KEY idx_problem_scan_figure_created (has_figure, created_at),
	CONSTRAINT fk_problem_scan_user_id FOREIGN KEY (user_id) REFERENCES users (id),
	CONSTRAINT fk_problem_scan_predicted_unit_id FOREIGN KEY (predicted_unit_id) REFERENCES unit (id),
	CONSTRAINT fk_problem_scan_predicted_type_id FOREIGN KEY (predicted_type_id) REFERENCES problem_type (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
