CREATE TABLE problem (
	id BIGINT NOT NULL AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	scan_id BIGINT NOT NULL,
	final_unit_id VARCHAR(50) NOT NULL,
	final_type_id VARCHAR(50) NOT NULL,
	render_mode VARCHAR(20) NOT NULL,
	problem_markdown MEDIUMTEXT NOT NULL,
	answer_format VARCHAR(20) NOT NULL,
	answer_value VARCHAR(255) NULL,
	answer_choice_no INT NULL,
	solution_text MEDIUMTEXT NULL,
	completed_at DATETIME(6) NULL,
	created_at DATETIME(6) NOT NULL,
	updated_at DATETIME(6) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE KEY uk_problem_scan_id (scan_id),
	KEY idx_problem_user_created (user_id, created_at),
	KEY idx_problem_unit (final_unit_id),
	KEY idx_problem_type (final_type_id),
	KEY idx_problem_render_created (render_mode, created_at),
	CONSTRAINT fk_problem_user_id FOREIGN KEY (user_id) REFERENCES users (id),
	CONSTRAINT fk_problem_scan_id FOREIGN KEY (scan_id) REFERENCES problem_scan (id),
	CONSTRAINT fk_problem_final_unit_id FOREIGN KEY (final_unit_id) REFERENCES unit (id),
	CONSTRAINT fk_problem_final_type_id FOREIGN KEY (final_type_id) REFERENCES problem_type (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
